# Generated by Django 6.1 on 2026-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Patna", max_length=180, verbose_name="city"
            ),
        ),
    ]
