# Define the backend API server
# "api" is the Docker Compose service name
# Django is running on port 8000 inside the api container
upstream api {
    server api:8000;
}


# Nginx server configuration
server {

    # Maximum size of request body
    # Allows file uploads/requests up to 20 MB
    client_max_body_size 20M;

    # Nginx listens for HTTP requests on port 80
    listen 80;


    # Send all /api/v1/ requests to Django
    #
    # Example:
    # http://localhost/api/v1/articles/
    #
    #        ↓
    #
    # http://api:8000/api/v1/articles/
    location /api/v1/ {

        # Forward request to the API container
        proxy_pass http://api;

        # Forward the client's IP address to Django
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Forward the original Host header
        proxy_set_header Host $host;

        # Don't modify redirects coming from Django
        proxy_redirect off;
    }


    # Send Django admin requests to Django
    # http://localhost/supersecret/
    #
    #        ↓
    #
    # Django admin
    location /supersecret {

        # Forward request to Django
        proxy_pass http://api;

        # Forward client's IP address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Forward original Host header
        proxy_set_header Host $host;

        # Don't modify Django redirects
        proxy_redirect off;
    }


    # Send ReDoc documentation requests to Django
    #
    # Example:
    # http://localhost/redoc/
    location /redoc {

        # Forward request to Django
        proxy_pass http://api;

        # Forward client's IP address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Forward original Host header
        proxy_set_header Host $host;

        # Don't modify Django redirects
        proxy_redirect off;
    }


    # Serve static files directly from Nginx
    #
    # URL:
    # /staticfiles/
    #
    # maps to:
    # /app/staticfiles/
    #
    # Example:
    #
    # /staticfiles/css/style.css
    #
    #        ↓
    #
    # /app/staticfiles/css/style.css
    location /staticfiles/ {

        # Tell Nginx where the static files are located
        alias /app/staticfiles/;
    }


    # Serve uploaded media files directly from Nginx
    #
    # URL:
    # /mediafiles/
    #
    # maps to:
    # /app/mediafiles/
    #
    # Example:
    #
    # /mediafiles/profile.jpg
    #
    #        ↓
    #
    # /app/mediafiles/profile.jpg
    location /mediafiles/ {

        # Tell Nginx where the media files are located
        alias /app/mediafiles/;
    }

}